version: '3'

services:
  jenkins:
    container_name: jenkins
    image: wltjd9870/jenkins:2.346.1-node-aws-docker-v1
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - 28080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: